project:
  type: website
  output-dir: _docs
  preview: 
    port: 3000
    browser: false
  render:
    - index.ipynb
    - data_creation.ipynb
    - detection_results.ipynb
    - test_area_observations.ipynb
    
format:
  html:
    theme: syke.scss
    toc: true
    page-layout: full
    
website:
  title: "Detecting marine vessels from Sentinel 2 data"
  description: "Detecting marine vessels from Sentinel 2 data"
  twitter-card:
    creator: "@mayrajeo"
  open-graph: true
  reader-mode: true
  repo-branch: main
  repo-subdir: nbs
  repo-url: https://github.com/mayrajeo/ship-detection
  repo-actions: [source]
  navbar:
    background: primary
    search: true
    right:
      - icon: github
        href: https://github.com/mayrajeo/ship-detection
  sidebar:
    style: "floating"
    contents:
      - text: Introduction
        file: index.ipynb
      - data_creation.ipynb
      - detection_results.ipynb
      - test_area_observations.ipynb
  page-navigation: true